/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class entriOrder extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksiDB.konek();
    
    /**
     * Creates new form userpesananFrame
     */
    public entriOrder() {
        initComponents();
        judul();
        tampilData("");
        idPesanan.setEnabled(false);
        idPelanggan.setEnabled(false);
        nmMenu.setEnabled(false);
        jumlah.setEnabled(false);
        harga.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * radminegenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        idPesanan = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nmMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        pesan1 = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("ID Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 60, 73, 19);

        idPesanan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idPesanan.setToolTipText("");
        getContentPane().add(idPesanan);
        idPesanan.setBounds(480, 85, 296, 33);

        jLabel3.setFont(new java.awt.Font("Bodoni MT Condensed", 1, 36)); // NOI18N
        jLabel3.setText("Form Order");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(566, 11, 138, 43);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Nama Menu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 205, 75, 19);

        nmMenu.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nmMenu.setToolTipText("");
        getContentPane().add(nmMenu);
        nmMenu.setBounds(480, 230, 296, 33);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Order");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 269, 85, 19);

        jumlah.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jumlah.setToolTipText("");
        getContentPane().add(jumlah);
        jumlah.setBounds(480, 294, 296, 33);

        pesan.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan.setText("Proses");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan);
        pesan.setBounds(480, 436, 145, 33);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Harga Satuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 338, 87, 19);

        harga.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        harga.setToolTipText("");
        getContentPane().add(harga);
        harga.setBounds(480, 368, 296, 33);

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("ID Pelanggan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 124, 85, 19);

        idPelanggan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idPelanggan.setToolTipText("");
        idPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(idPelanggan);
        idPelanggan.setBounds(480, 149, 296, 33);

        pesan1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan1.setText("Logout");
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan1);
        pesan1.setBounds(631, 436, 145, 33);

        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali);
        btnkembali.setBounds(480, 487, 296, 38);

        jPanel1.setBackground(new java.awt.Color(255, 94, 58));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(44, 53, 93));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orderan Masuk");

        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 125, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 20, 470, 490);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 790, 560);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(480, 50, 100, 100);

        setSize(new java.awt.Dimension(806, 601));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO transaksi VALUES (null,'"+idPesanan.getText()+"','"+idPelanggan.getText()+"','"+nmMenu.getText()+"','"+jumlah.getText()+"','"+harga.getText()+"',0,0,0,'Unpaid')");

       
            JOptionPane.showMessageDialog(null, "Orderan berhasil diproses.");
            entriOrder eo = new entriOrder();
            eo.show();
            this.dispose();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesanActionPerformed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
        idPesanan.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),0).toString());
        idPelanggan.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),1).toString());
        nmMenu.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),2).toString());
        jumlah.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),3).toString());
        harga.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),4).toString());

    }//GEN-LAST:event_tbMenuMouseClicked

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
        loginFrame lf = new loginFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_pesan1ActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
         waiterFrame lf = new waiterFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void idPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idPelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idPelangganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananFrame().setVisible(true);
            }
        });
    }
    public void judul(){
        Object[] judul = {
            "ID Pesanan","ID Pelanggan", "Nama Menu","Jumlah Pembelian", "Harga"
        };
        tabModel = new DefaultTableModel(null,judul);
        tbMenu.setModel(tabModel);
    }
    public void tampilData(String pesanan){
        try{
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM pesanan INNER JOIN menu ON pesanan.idMenu = menu.idMenu");                       

            
            while(rs.next()){
                Object[] data = {
                    rs.getString("idPesanan"),
                    rs.getString("idPelanggan"),
                    rs.getString("nmMenu"),
                    rs.getString("jumlah"),
                    rs.getString("harga"),
                    

                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JTextField idPesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField nmMenu;
    private javax.swing.JButton pesan;
    private javax.swing.JButton pesan1;
    private javax.swing.JTable tbMenu;
    // End of variables declaration//GEN-END:variables
}
