/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class entriTransaksi extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksiDB.konek();
    
    /**
     * Creates new form userpesananFrame
     */
    public entriTransaksi() {
        initComponents();
        judul();
        tampilData("");
        idTransaksi.setEnabled(false);
        idPesanan.setEnabled(false);
        idPelanggan.setEnabled(false);
        nmMenu.setEnabled(false);
        jumlah.setEnabled(false);
        harga.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idPesanan = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        nmMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        pesan1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        total = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        bayar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        kembalian = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        idTransaksi = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbMenu.setForeground(new java.awt.Color(255, 102, 102));
        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 72, 845, 613);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("ID Pesanan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(861, 72, 73, 19);

        idPesanan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idPesanan.setToolTipText("");
        getContentPane().add(idPesanan);
        idPesanan.setBounds(861, 97, 217, 33);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Nama Menu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(861, 136, 75, 19);

        nmMenu.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nmMenu.setToolTipText("");
        getContentPane().add(nmMenu);
        nmMenu.setBounds(861, 161, 217, 33);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Order");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(1100, 136, 85, 19);

        jumlah.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jumlah.setToolTipText("");
        getContentPane().add(jumlah);
        jumlah.setBounds(1100, 161, 224, 33);

        pesan.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan.setText("Bayar");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan);
        pesan.setBounds(861, 609, 309, 33);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Harga Satuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(861, 200, 87, 19);

        harga.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        harga.setToolTipText("");
        getContentPane().add(harga);
        harga.setBounds(861, 225, 217, 33);

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel7.setText("Status");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(1100, 200, 40, 19);

        status.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paid", "UnPaid" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        getContentPane().add(status);
        status.setBounds(1100, 225, 224, 33);

        jLabel8.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel8.setText("ID Pelanggan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(1104, 72, 85, 19);

        idPelanggan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idPelanggan.setToolTipText("");
        getContentPane().add(idPelanggan);
        idPelanggan.setBounds(1104, 97, 220, 33);

        pesan1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan1.setText("Logout");
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan1);
        pesan1.setBounds(1188, 609, 136, 33);

        jLabel9.setFont(new java.awt.Font("Source Sans Pro", 1, 24)); // NOI18N
        jLabel9.setText("DETAIL PAYMENT");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(968, 269, 211, 31);

        jLabel10.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel10.setText("Total Harga");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(861, 372, 74, 19);

        total.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        total.setToolTipText("");
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        getContentPane().add(total);
        total.setBounds(861, 397, 278, 33);

        jLabel11.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel11.setText("Uang Bayar");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(861, 438, 74, 19);

        bayar.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        bayar.setToolTipText("");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });
        getContentPane().add(bayar);
        bayar.setBounds(861, 487, 463, 33);

        jLabel12.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel12.setText("Uang Kembalian");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(861, 526, 103, 19);

        kembalian.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        kembalian.setToolTipText("");
        kembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembalianActionPerformed(evt);
            }
        });
        getContentPane().add(kembalian);
        kembalian.setBounds(861, 551, 309, 33);

        jLabel13.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel13.setText("ID Transaksi");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(861, 298, 79, 19);

        idTransaksi.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idTransaksi.setToolTipText("");
        getContentPane().add(idTransaksi);
        idTransaksi.setBounds(861, 328, 463, 33);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setText("Hitung");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1188, 553, 136, 33);

        jButton2.setText("Total");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(1186, 399, 137, 33);

        jPanel1.setBackground(new java.awt.Color(255, 94, 58));

        jPanel3.setBackground(new java.awt.Color(44, 53, 93));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Orderan Masuk");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Form Transaksi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 406, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(140, 140, 140))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 630, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 700);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(920, 10, 100, 100);

        setSize(new java.awt.Dimension(1400, 735));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE transaksi SET total = '"+total.getText()+"',bayar = '"+bayar.getText()+"',kembalian = '"+kembalian.getText()+"', status = '"+status.getSelectedItem()+"' WHERE idTransaksi = '"+idTransaksi.getText()+"'");

       
            JOptionPane.showMessageDialog(null, "Transaksi Selesai");
            entriTransaksi et = new entriTransaksi();
            et.show();
            this.dispose();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesanActionPerformed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
        idTransaksi.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),0).toString());
        idPesanan.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),1).toString());
        idPelanggan.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),2).toString());
        nmMenu.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),3).toString());
        jumlah.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),4).toString());
        harga.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),5).toString());
        
    }//GEN-LAST:event_tbMenuMouseClicked

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
        loginFrame lf = new loginFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_pesan1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int totalharga = Integer.parseInt(jumlah.getText())*Integer.parseInt(harga.getText());
        int bayr = Integer.parseInt(bayar.getText());
        int kemb = bayr-totalharga;
        kembalian.setText(""+kemb);
                
    }//GEN-LAST:event_jButton1ActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int totalharga = Integer.parseInt(jumlah.getText())*Integer.parseInt(harga.getText());
        total.setText(""+totalharga);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void kembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembalianActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kembalianActionPerformed

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed

         // TODO add your handling code here:
    }//GEN-LAST:event_bayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananFrame().setVisible(true);
            }
        });
    }
    public void judul(){
        Object[] judul = {
            "ID Transaksi","ID Pesanan","Nama Pelanggan", "Nama Menu","Jumlah Pembelian", "Harga", "Status"
        };
        tabModel = new DefaultTableModel(null,judul);
        tbMenu.setModel(tabModel);
    }
    public void tampilData(String pesanan){
        try{
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM transaksi INNER JOIN pelanggan ON transaksi.idPelanggan = pelanggan.idPelanggan");                       

            
            while(rs.next()){
                Object[] data = {
                    rs.getString("idTransaksi"),
                    rs.getString("idPesanan"),
                    rs.getString("nmPelanggan"),
                    rs.getString("nmMenu"),
                    rs.getString("jumlah"),
                    rs.getString("harga"),
                    rs.getString("status"),
                    

                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bayar;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JTextField idPesanan;
    private javax.swing.JTextField idTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kembalian;
    private javax.swing.JTextField nmMenu;
    private javax.swing.JButton pesan;
    private javax.swing.JButton pesan1;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable tbMenu;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
