/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class entriMenu extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksiDB.konek();
    
    /**
     * Creates new form userpesananFrame
     */
    public entriMenu() {
        initComponents();
        judul();
        tampilData("");
        idMenu.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        idMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        nmMenu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        pesan = new javax.swing.JButton();
        pesan1 = new javax.swing.JButton();
        pesan2 = new javax.swing.JButton();
        pesan3 = new javax.swing.JButton();
        btnkembali = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbMenu.setBackground(new java.awt.Color(240, 240, 240));
        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMenu.setSelectionBackground(new java.awt.Color(102, 102, 102));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 79, 452, 110);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("ID Menu ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(519, 138, 56, 19);

        idMenu.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idMenu.setToolTipText("Masukan username anda");
        idMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idMenuActionPerformed(evt);
            }
        });
        getContentPane().add(idMenu);
        idMenu.setBounds(603, 131, 220, 33);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Cond", 1, 36)); // NOI18N
        jLabel3.setText("Form Menu");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(576, 11, 192, 47);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("Nama Menu");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(510, 214, 75, 19);

        nmMenu.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        nmMenu.setToolTipText("Masukan username anda");
        nmMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmMenuActionPerformed(evt);
            }
        });
        getContentPane().add(nmMenu);
        nmMenu.setBounds(603, 200, 220, 33);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Harga");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(528, 276, 38, 19);

        harga.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        harga.setToolTipText("Masukan username anda");
        harga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaActionPerformed(evt);
            }
        });
        getContentPane().add(harga);
        harga.setBounds(603, 269, 220, 33);

        pesan.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan.setText("Tambah");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan);
        pesan.setBounds(487, 337, 145, 33);

        pesan1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan1.setText("Perbarui");
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan1);
        pesan1.setBounds(650, 337, 162, 33);

        pesan2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan2.setText("Hapus");
        pesan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan2ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan2);
        pesan2.setBounds(487, 388, 145, 33);

        pesan3.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan3.setText("Logout");
        pesan3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan3ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan3);
        pesan3.setBounds(650, 388, 162, 33);

        btnkembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnkembali.setText("Kembali");
        btnkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnkembali);
        btnkembali.setBounds(487, 520, 327, 25);

        jPanel1.setBackground(new java.awt.Color(255, 94, 58));
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(44, 53, 93));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jLabel1)
                .addContainerGap(197, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(366, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(50, 30, 470, 420);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-40, -20, 870, 480);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(80, 10, 210, 140);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(290, 40, 100, 100);

        setSize(new java.awt.Dimension(845, 498));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO menu VALUES (null,'"+nmMenu.getText()+"','"+harga.getText()+"')");

       
            JOptionPane.showMessageDialog(null, "Menu Berhasil diTambahkan.");
            entriMenu em = new entriMenu();
            em.show();
            this.dispose();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesanActionPerformed

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("UPDATE menu SET nmMenu = '"+nmMenu.getText()+"',harga = '"+harga.getText()+"' WHERE idMenu = '"+idMenu.getText()+"'");

       
            JOptionPane.showMessageDialog(null, "Menu Berhasil diUpdate.");
            entriMenu em = new entriMenu();
            em.show();
            this.dispose();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesan1ActionPerformed

    private void pesan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan2ActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("DELETE FROM menu WHERE idMenu = '"+idMenu.getText()+"'");

       
            JOptionPane.showMessageDialog(null, "Menu Berhasil diHapus.");
            entriMenu em = new entriMenu();
            em.show();
            this.dispose();
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesan2ActionPerformed

    private void pesan3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan3ActionPerformed
        loginFrame lf = new loginFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_pesan3ActionPerformed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
        idMenu.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),0).toString());
        nmMenu.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),1).toString());
        harga.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),2).toString());

    }//GEN-LAST:event_tbMenuMouseClicked

    private void nmMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nmMenuActionPerformed

    private void btnkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkembaliActionPerformed
        // TODO add your handling code here:
                waiterFrame lf = new waiterFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_btnkembaliActionPerformed

    private void idMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idMenuActionPerformed

    private void hargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananFrame().setVisible(true);
            }
        });
    }
    public void judul(){
        Object[] judul = {
            "ID Menu","Nama Menu","harga"
        };
        tabModel = new DefaultTableModel(null,judul);
        tbMenu.setModel(tabModel);
    }
    public void tampilData(String pesanan){
        try{
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM menu");
            
            while(rs.next()){
                Object[] data = {
                    rs.getString("idMenu"),
                    rs.getString("nmMenu"),
                    rs.getString("harga")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnkembali;
    private javax.swing.JTextField harga;
    private javax.swing.JTextField idMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nmMenu;
    private javax.swing.JButton pesan;
    private javax.swing.JButton pesan1;
    private javax.swing.JButton pesan2;
    private javax.swing.JButton pesan3;
    private javax.swing.JTable tbMenu;
    // End of variables declaration//GEN-END:variables
}
