/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class pemesananFrame extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksiDB.konek();
    
    /**
     * Creates new form userpesananFrame
     */
    public pemesananFrame() {
        initComponents();
        judul();
        tampilData("");
        
        idMenu.setEnabled(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbMenu = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idMenu = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        idPelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cariID = new javax.swing.JTextField();
        nmPelanggan = new javax.swing.JButton();
        pesan = new javax.swing.JButton();
        pesan1 = new javax.swing.JButton();
        pesan2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        tbMenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbMenu);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 64, 452, 349);

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Menu");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(202, 11, 91, 47);

        jLabel2.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel2.setText("ID Menu ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 64, 56, 19);

        idMenu.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idMenu.setToolTipText("Masukan username anda");
        getContentPane().add(idMenu);
        idMenu.setBounds(480, 89, 311, 33);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Form Pemesanan");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(466, 11, 301, 47);

        jLabel4.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel4.setText("ID Pelanggan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 133, 85, 19);

        idPelanggan.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        idPelanggan.setToolTipText("Masukan username anda");
        getContentPane().add(idPelanggan);
        idPelanggan.setBounds(480, 158, 311, 33);

        jLabel5.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel5.setText("Jumlah Pesanan");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 202, 104, 19);

        jumlah.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        jumlah.setToolTipText("Masukan username anda");
        getContentPane().add(jumlah);
        jumlah.setBounds(480, 227, 311, 33);

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        jLabel6.setText("Cari ID, Masukan Nama Pelanggan Anda  :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 419, 269, 19);

        cariID.setFont(new java.awt.Font("Source Sans Pro", 0, 14)); // NOI18N
        cariID.setToolTipText("Masukan username anda");
        getContentPane().add(cariID);
        cariID.setBounds(10, 444, 269, 37);

        nmPelanggan.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        nmPelanggan.setText("Cari");
        nmPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nmPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(nmPelanggan);
        nmPelanggan.setBounds(285, 444, 177, 37);

        pesan.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan.setText("Pesan Makanan");
        pesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesanActionPerformed(evt);
            }
        });
        getContentPane().add(pesan);
        pesan.setBounds(480, 286, 311, 33);

        pesan1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan1.setText("Kembali");
        pesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan1ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan1);
        pesan1.setBounds(480, 325, 311, 33);

        pesan2.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        pesan2.setText("Close Aplikasi");
        pesan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesan2ActionPerformed(evt);
            }
        });
        getContentPane().add(pesan2);
        pesan2.setBounds(480, 364, 311, 33);

        jPanel1.setBackground(new java.awt.Color(255, 94, 58));

        jPanel3.setBackground(new java.awt.Color(44, 53, 93));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 63, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 427, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 490);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(380, 30, 100, 100);

        setSize(new java.awt.Dimension(817, 526));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nmPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nmPelangganActionPerformed
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT idPelanggan FROM pelanggan WHERE nmPelanggan = '"+cariID.getText()+"'");
            
            if(rs.next()){
                JOptionPane.showMessageDialog(null, "ID Anda : " + rs.getString("idPelanggan"));
                cariID.setText("");
            }else{
                JOptionPane.showMessageDialog(null, "Maaf Tidak Dapat Menemukan ID, Periksa Nama Pelanggan");
                cariID.setText("");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_nmPelangganActionPerformed

    private void pesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesanActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("INSERT INTO pesanan VALUES (null,'"+idMenu.getText()+"','"+idPelanggan.getText()+"','"+jumlah.getText()+"')");

       
            JOptionPane.showMessageDialog(null, "Pesanan Masuk, Harap Tunggu !");
            idMenu.setText("");
            idPelanggan.setText("");
            jumlah.setText("");
                  
            
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_pesanActionPerformed

    private void tbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMenuMouseClicked
                idMenu.setText(tbMenu.getValueAt(tbMenu.getSelectedRow(),0).toString());
    }//GEN-LAST:event_tbMenuMouseClicked

    private void pesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan1ActionPerformed
        loginFrame lf = new loginFrame();
        lf.show();
        this.dispose();
    }//GEN-LAST:event_pesan1ActionPerformed

    private void pesan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesan2ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_pesan2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pemesananFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pemesananFrame().setVisible(true);
            }
        });
    }
    public void judul(){
        Object[] judul = {
            "ID Menu","Nama Menu","harga"
        };
        tabModel = new DefaultTableModel(null,judul);
        tbMenu.setModel(tabModel);
    }
    public void tampilData(String pesanan){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM menu");
            
            while(rs.next()){
                Object[] data = {
                    rs.getString("idMenu"),
                    rs.getString("nmMenu"),
                    rs.getString("harga")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cariID;
    private javax.swing.JTextField idMenu;
    private javax.swing.JTextField idPelanggan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton nmPelanggan;
    private javax.swing.JButton pesan;
    private javax.swing.JButton pesan1;
    private javax.swing.JButton pesan2;
    private javax.swing.JTable tbMenu;
    // End of variables declaration//GEN-END:variables
}
